place_list.push(
    ["Brettspielmesse","Gamescom","eva_words"],
    ["Bauernhof","Streichelzoo","eva_words"],
    ["Second Hand shop","Begehbarer Kleiderschrank","eva_words"],
    ["Baumarkt","Hochseilgarten","eva_words"],
    ["Flussbiegung","Deich","eva_words"],
    ["Meeresboden","Raumschiff","eva_words"],
    ["Dungeon","Labyrinth","eva_words"],
    ["Streuobstwiese","Maisfeld","eva_words"],
    ["Safari","Jungel","eva_words"],
    ["Hochzeit","Jahrmarkt","eva_words"],
    ["Gefängnis","U-Boot","eva_words"],
    ["Matratzenfachgeschäft","Buchladen","eva_words"],
    ["Gärtnerei","Botanischer Garten","eva_words"],
    ["Schmetterlingshaus","Greifvogelshow","eva_words"],
    ["Wetterbalon","Heißluftballon","eva_words"],
    ["Mondlandschaft","Sahara","eva_words"],
    ["Mediamarkt","Spielsalon","eva_words"],
    ["Gewächshaus","Orangerie","eva_words"],
    ["Lichterkette","Kronleuchter","eva_words"],
    ["Bierzelt","Disco","eva_words"],
);