place_list.push(
    ["Zoo","Aquarium","everyday"],
    ["Beach","Swimming pool","everyday"],
    ["Ski resort","Skate park","everyday"],
    ["Church","Courthouse","everyday"],
    ["Playground","Arcade","everyday"],
    ["Bowling alley","Mini-golf course","everyday"],
    ["Laundromat","Dry cleaner","everyday"],
    ["Bakery","Ice cream parlor","everyday"],
    ["Post office","Courier service","everyday"],
    ["Bank","Casino","everyday"],
    ["Pharmacy","Health food store","everyday"],
    ["Pet store","Animal shelter","everyday"],
    ["Amusement park","State fair","everyday"],
    ["Nightclub","Comedy club","everyday"],
    ["Tattoo parlor","Piercing studio","everyday"],
    ["Yoga studio","Martial arts dojo","everyday"],
    ["Antique shop","Thrift store","everyday"],
    ["Car dealership","Bike shop","everyday"],
    ["Florist","Garden center","everyday"],
    ["Tailor","Costume shop","everyday"],
    ["Furniture store","Flea market","everyday"],
    ["Diner","Food truck","everyday"],
    ["Daycare center","Senior center","everyday"],
    ["Barber shop","Beauty salon","everyday"],
    ["Bookstore","Comic book shop","everyday"],
    ["Dentist office","Orthodontist office","everyday"],
    ["Karaoke bar","Piano bar","everyday"],
    ["Butcher shop","Vegan cafe","everyday"],
    ["Winery","Brewery","everyday"],
    ["Shoe store","Hat shop","everyday"],
    ["Pawn shop","Auction house","everyday"],
    ["Tanning salon","Spray tan booth","everyday"],
    ["Optometrist","Eyeglass store","everyday"],
    ["Record store","Music school","everyday"],
    ["Travel agency","Luggage store","everyday"],
    ["Fishing pier","Hunting lodge","everyday"],
    ["Pottery studio","Glass blowing workshop","everyday"],
    ["Escape room","Laser tag arena","everyday"],
    ["Psychic reader","Fortune cookie factory","everyday"],
    ["Driving range","Miniature golf course","everyday"],
    ["Rock climbing gym","Bouldering cave","everyday"],
    ["Trampoline park","Roller skating rink","everyday"]
);