place_list.push(
    ["Terminator","Transformer","AI_safety_beginner"],
    ["University","ML4good","AI_safety_beginner"],
    ["Machine Learning","pytorch","AI_safety_beginner"],
    ["X-Risk", "The Singularity", "AI_safety_beginner"],
    ["Alan Turing","Sam Altman","AI_safety_beginner"],
    ["Nvidia","(Google) DeepMind","AI_safety_beginner"],
    ["Paperclip Maximizer", "Instrumental Convergence", "AI_safety_advanced"],
    ["Reward Hacking", "Goodhart's Law", "AI_safety_advanced"],
    ["Nick Bostrom", "Stuart Russell", "AI_safety_advanced"],
    ["Longtermism", "Effective Accelerationism (e/acc)", "AI_safety_advanced"],
    ["Attention Head", "Feature", "AI_safety_advanced"],
    ["Reward Function", "Gradient Descent", "AI_safety_advanced"],
    ["Paperclips", "Coherent Extrapolated Volition (CEV)", "AI_safety_advanced"],
    ["GPU", "GPT", "AI_safety_advanced"],
    ["Corrigibility", "Interpretability", "AI_safety_advanced"],
);