place_list.push(
    ["The Pyramids of Giza","Angkor Wat","specific"],
    ["The Grand Canyon","The Cliffs of Moher","specific"],
    ["Mount Fuji","The Alps","specific"],
    ["The Serengeti","Yellowstone National Park","specific"],
    ["The Acropolis","Chichen Itza","specific"],
    ["The Dead Sea","Lake Baikal","specific"],
    ["The Galapagos Islands","Madagascar","specific"],
    ["The Amazon River","The Nile River","specific"],
    ["The Himalayas","The Andes","specific"],
    ["The Red Square","Times Square","specific"],
    ["The Louvre","The Uffizi Gallery","specific"],
    ["The Sydney Opera House","The Bolshoi Theatre","specific"],
    ["Venice Canals","The Suez Canal","specific"],
    ["Victoria Falls","Niagara Falls","specific"],
    ["The Great Barrier Reef","The Maldives","specific"],
    ["Petra","Mesa Verde National Park","specific"],
    ["Mount Kilimanjaro","Mount Elbrus","specific"],
    ["The Mojave Desert","The Gobi Desert","specific"],
    ["The Amazon Basin","The Congo Basin","specific"],
    ["The Golden Gate Bridge","The Tower Bridge","specific"],
    ["The Forbidden City","The Alhambra","specific"],
    ["The Arctic Circle","The Antarctic Peninsula","specific"],
    ["The Okavango Delta","The Pantanal","specific"],
    ["The Blue Lagoon","The Hot Springs of Iceland","specific"],
    ["The Everglades","The Daintree Rainforest","specific"],
    ["The Sahara Dunes","The White Sands National Monument","specific"],
    ["The Sphinx","Easter Island Statues","specific"],
    ["The Ngorongoro Crater","The Grand Canyon","specific"],
    ["The Baltic Sea","The Adriatic Sea","specific"],
    ["The Banaue Rice Terraces","The Valley of the Kings","specific"]
);
