place_list.push(
    ["Times Square","Red Square","specific"],
    ["Hollywood Sign","London Eye","specific"],
    ["Central Park","Hyde Park","specific"],
    ["Notre Dame Cathedral","Westminster Abbey","specific"],
    ["Mount Rushmore","Sphinx","specific"],
    ["Leaning Tower of Pisa","CN Tower","specific"],
    ["Vatican City","Mecca","specific"],
    ["Great Barrier Reef","Amazon Rainforest","specific"],
    ["Venetian Canals","Panama Canal","specific"],
    ["Alcatraz","Tower of London","specific"],
    ["Grand Canyon","Niagara Falls","specific"],
    ["Statue of Liberty","Christ the Redeemer","specific"],
    ["Eiffel Tower","Tokyo Tower","specific"],
    ["Pyramids of Giza","Stonehenge","specific"],
    ["Colosseum","Acropolis","specific"],
    ["Great Wall of China","Berlin Wall","specific"],
    ["Mount Everest","Alps","specific"],
    ["Taj Mahal","Kremlin","specific"],
    ["Golden Gate Bridge","Brooklyn Bridge","specific"],
    ["White House","Buckingham Palace","specific"],
    ["Louvre Museum","Hermitage Museum","specific"],
    ["Yellowstone National Park","Serengeti National Park","specific"],
    ["Sagrada Familia","St. Peter's Basilica","specific"],
    ["Machu Picchu","Chichen Itza","specific"],
    ["Venice Canals","Amsterdam Canals","specific"],
    ["Sistine Chapel","Hagia Sophia","specific"],
    ["Galapagos Islands","Maldives","specific"],
    ["Neuschwanstein Castle","Palace of Versailles","specific"],
    ["Uluru (Ayers Rock)","Table Mountain","specific"],
    ["Pompeii","Ephesus","specific"]
);